### ISSUE TITLE
Password is being displayed when the user presses enter to log in

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#1400]
### Terms

- [x] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [x] I agree to follow activist's [Code of Conduct](.github/CODE_OF_CONDUCT.md)

### Behavior

We have an issue where when the use signs in to the frontend at `auth/sign-in` with the admin username and password `admin` `admin` the password is shown to the user for an instant before they're navigated to the home page. This needs to be fixed so that people's passwords won't be displayed and always will be hidden.

**Comment by amyanger** [comment]
@andrewtavis Would you mind me taking this one on? :)

**Comment by andrewtavis** [comment]
Sounds great, @arjun-myanger! Please let us know if we can assist you with this :) We'd be happy to help!

**Comment by amyanger** [comment]
> Sounds great, @arjun-myanger! Please let us know if we can assist you with this :) We'd be happy to help!

I think I fixed it for you, seems someone left a console.log in and forgot about it. This is my second pull request so sorry if I did anything wrong but I hope it works for you now! @andrewtavis

**Comment by andrewtavis** [comment]
Sorry to reopen, @amyanger 🤔 This was working for some initial tests, but now I'm still getting that the password shows when the user hits enter. More to the point, we have that the form is being submitted if the user presses the eye icon to view the password. Maybe this is a related issue 🤔

**Comment by amyanger** [comment]
Interesting, I will have a look into this. I didn't notice this issue on my tests, might have missed it or something. @andrewtavis

**Comment by andrewtavis** [comment]
Thanks for keeping at this, @amyanger! :)
